#!/bin/bash
# =============================================================================
# G1 Robot Network Setup Script
# =============================================================================
# Configures host network interface for robot communication.
# Sets up CycloneDDS configuration automatically.
#
# Usage:
#   ./scripts/setup-network.sh [interface]
#
# If no interface specified, will auto-detect or prompt.
# =============================================================================

set -e

# Network configuration (fixed by Unitree hardware)
ROBOT_IP="192.168.123.164"
LIDAR_IP="192.168.123.120"
SUBNET="192.168.123"
HOST_IP="${SUBNET}.10"  # Default host IP if needs assignment

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CYCLONE_CONFIG="${PROJECT_ROOT}/config/cyclonedds.xml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "============================================================"
echo "     G1 ROBOT NETWORK SETUP"
echo "============================================================"
echo
echo "Robot IP:  ${ROBOT_IP}"
echo "Subnet:    ${SUBNET}.0/24"
echo

# Function to find interface on robot subnet
find_robot_interface() {
    ip addr 2>/dev/null | grep "${SUBNET}" | awk '{print $NF}' | head -1
}

# Function to list available ethernet interfaces
list_interfaces() {
    ip link show 2>/dev/null | grep -E "^[0-9]+:" | awk '{print $2}' | tr -d ':' | grep -v "^lo$"
}

# Check if interface was provided as argument
IFACE="$1"

if [ -z "$IFACE" ]; then
    # Try to auto-detect
    IFACE=$(find_robot_interface)

    if [ -z "$IFACE" ]; then
        echo -e "${YELLOW}[INFO]${NC} No interface found on robot subnet."
        echo
        echo "Available interfaces:"
        list_interfaces | while read iface; do
            echo "  - $iface"
        done
        echo
        read -p "Enter interface to configure (e.g., eth0, enp3s0): " IFACE

        if [ -z "$IFACE" ]; then
            echo -e "${RED}[ERROR]${NC} No interface specified. Exiting."
            exit 1
        fi
    else
        echo -e "${GREEN}[OK]${NC} Auto-detected interface: $IFACE"
    fi
fi

# Check if interface exists
if ! ip link show "$IFACE" &>/dev/null; then
    echo -e "${RED}[ERROR]${NC} Interface '$IFACE' not found!"
    exit 1
fi

echo
echo -e "${BLUE}[SETUP]${NC} Configuring interface: $IFACE"

# Check if already on robot subnet
CURRENT_IP=$(ip addr show "$IFACE" 2>/dev/null | grep "${SUBNET}" | awk '{print $2}' | cut -d'/' -f1)

if [ -n "$CURRENT_IP" ]; then
    echo -e "${GREEN}[OK]${NC} Interface already configured: $CURRENT_IP"
    HOST_IP="$CURRENT_IP"
else
    echo -e "${YELLOW}[INFO]${NC} Interface needs IP assignment on robot subnet."
    echo
    echo "This will run: sudo ip addr add ${HOST_IP}/24 dev ${IFACE}"
    read -p "Proceed? [y/N] " confirm

    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        sudo ip addr add "${HOST_IP}/24" dev "$IFACE" 2>/dev/null || {
            echo -e "${YELLOW}[WARN]${NC} IP may already be assigned, continuing..."
        }
        sudo ip link set "$IFACE" up
        echo -e "${GREEN}[OK]${NC} Assigned ${HOST_IP} to ${IFACE}"
    else
        echo -e "${YELLOW}[SKIP]${NC} Skipping IP assignment."
    fi
fi

# Generate CycloneDDS config with specific interface
echo
echo -e "${BLUE}[SETUP]${NC} Generating CycloneDDS configuration..."

cat > "$CYCLONE_CONFIG" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- CycloneDDS Configuration for G1 Robot Communication -->
<!-- Generated by: scripts/setup-network.sh -->
<!-- Robot static IP: ${ROBOT_IP} -->
<CycloneDDS xmlns="https://cdds.io/config">
  <Domain id="0">
    <General>
      <!-- Host interface for robot communication -->
      <NetworkInterfaceAddress>${HOST_IP}</NetworkInterfaceAddress>
    </General>
    <Discovery>
      <!-- G1 Robot endpoint -->
      <Peers>
        <Peer address="${ROBOT_IP}"/>
      </Peers>
    </Discovery>
  </Domain>
</CycloneDDS>
EOF

echo -e "${GREEN}[OK]${NC} Wrote: $CYCLONE_CONFIG"

# Test connectivity
echo
echo -e "${BLUE}[TEST]${NC} Testing robot connectivity..."

if ping -c 2 -W 2 "$ROBOT_IP" &>/dev/null; then
    echo -e "${GREEN}[OK]${NC} Robot is reachable at ${ROBOT_IP}"
else
    echo -e "${YELLOW}[WARN]${NC} Robot not responding. Make sure it's powered on."
fi

echo
echo "============================================================"
echo -e "${GREEN}Network setup complete!${NC}"
echo
echo "Environment variable (add to shell or .env):"
echo "  export CYCLONEDDS_URI=file://${CYCLONE_CONFIG}"
echo "============================================================"
